// src/components/products/ProductCard.jsx
import { FaWhatsapp } from 'react-icons/fa'

export default function ProductCard({ product }) {
  const discount = product.originalPrice
    ? Math.round(((parseInt(product.originalPrice.replace(/,/g, '')) - parseInt(product.price.replace(/,/g, ''))) / parseInt(product.originalPrice.replace(/,/g, ''))) * 100)
    : 0

  return (
    <div className="group bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-card-hover transition-all duration-300 hover:-translate-y-1 border border-gray-100 flex flex-col">
      <div className="relative h-56 overflow-hidden bg-gray-100">
        <img
          src={product.image}
          alt={product.name}
          className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
        />
        <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300" />
        <div className="absolute top-4 left-4 flex gap-2">
          {discount > 0 && (
            <span className="bg-primary text-white text-xs font-semibold px-3 py-1 rounded-full shadow-sm">
              -{discount}% OFF
            </span>
          )}
        </div>
        <div className="absolute top-4 right-4">
          <span className={`text-xs font-semibold px-3 py-1 rounded-full shadow-sm ${
            product.available
              ? 'bg-green-500 text-white'
              : 'bg-red-500 text-white'
          }`}>
            {product.available ? 'Available' : 'Sold Out'}
          </span>
        </div>
      </div>

      <div className="p-6 flex flex-col flex-1">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xs font-medium text-gray-600 bg-gray-100 px-2.5 py-1 rounded-md">
            {product.brand}
          </span>
          <span className="text-xs font-medium text-gray-600 bg-gray-100 px-2.5 py-1 rounded-md">
            {product.condition}
          </span>
        </div>

        <h3 className="text-lg font-bold text-gray-900 mb-2 group-hover:text-primary transition-colors">
          {product.name}
        </h3>

        <p className="text-sm text-gray-600 mb-3">
          {product.specs}
        </p>

        <p className="text-xs text-gray-500 mb-4 line-clamp-2">
          {product.description}
        </p>

        <div className="flex items-end gap-3 mb-5 mt-auto">
          <span className="text-2xl font-extrabold text-primary">₦{product.price}</span>
          {product.originalPrice && (
            <span className="text-sm text-gray-400 line-through mb-0.5">₦{product.originalPrice}</span>
          )}
        </div>

        <a
          href={`https://wa.me/2348026295718?text=Hi, I'm interested in the ${product.name} (${product.specs}) - ₦${product.price}`}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center justify-center gap-2 w-full bg-green-500 text-white font-semibold py-3 rounded-xl hover:bg-green-600 hover:shadow-lg transition-all duration-300"
        >
          <FaWhatsapp />
          Buy via WhatsApp
        </a>
      </div>
    </div>
  )
}

// frontend_/src/components/ProductCard.svelte
<script>
  export let product;
  import { cart, toast } from '../lib/stores.js';

  function addToCart() {
    cart.addItem(product);
    toast.add(`${product.name} added to cart!`, 'success');
  }

  function formatPrice(price) {
    return new Intl.NumberFormat('en-NG', {
      style: 'currency',
      currency: 'NGN'
    }).format(price);
  }
</script>

<div class="card hover:shadow-lg transition-shadow duration-300 h-full flex flex-col">
  <div class="relative mb-4">
    <img 
      src={product.image || '/images/products/laptop-placeholder.svg'} 
      alt={product.name}
      class="w-full h-48 object-cover rounded-lg"
    />
    {#if !product.inStock}
      <span class="absolute top-2 right-2 bg-red-500 text-white px-2 py-1 rounded text-xs font-semibold">
        Out of Stock
      </span>
    {:else if product.quantity < 5}
      <span class="absolute top-2 right-2 bg-yellow-500 text-white px-2 py-1 rounded text-xs font-semibold">
        Low Stock
      </span>
    {/if}
  </div>

  <div class="flex-1 flex flex-col">
    <h3 class="text-lg font-semibold text-gray-900 mb-2">{product.name}</h3>
    <p class="text-gray-600 text-sm mb-3 line-clamp-2">{product.description}</p>
    
    {#if product.specs}
      <div class="space-y-1 mb-3">
        {#each Object.entries(product.specs || {}).slice(0, 3) as [key, value]}
          <p class="text-xs text-gray-500">
            <span class="font-medium">{key}:</span> {value}
          </p>
        {/each}
      </div>
    {/if}

    <div class="flex items-center justify-between mt-auto">
      <span class="text-xl font-bold text-primary-600">
        {formatPrice(product.price)}
      </span>
      <span class="text-xs text-gray-500 bg-gray-100 px-2 py-1 rounded">
        {product.category}
      </span>
    </div>
  </div>

  <div class="mt-4 flex space-x-2">
    <a 
      href="/shop/{product.id}" 
      class="flex-1 bg-gray-100 hover:bg-gray-200 text-gray-800 font-medium py-2 px-4 rounded text-center transition-colors duration-200"
    >
      View Details
    </a>
    {#if product.inStock}
      <button 
        on:click={addToCart}
        class="flex-1 btn-primary"
      >
        Add to Cart
      </button>
    {:else}
      <button 
        disabled
        class="flex-1 bg-gray-300 text-gray-500 font-medium py-2 px-4 rounded cursor-not-allowed"
      >
        Out of Stock
      </button>
    {/if}
  </div>
</div>

<style>
  .line-clamp-2 {
    display: -webkit-box;
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
  }
</style>
